import pandas as pd
df=pd.read_excel("job_dataset.xlsx")
print(df.head())
print("\n Dataset Shape:")
print(df.shape)
print("\n columns:")
print(df.columns)
print("\n Total Jobs:")
print(len(df))
print("\n Top 10 Hiring Companies:")
print(df["company_name"].value_counts().head(10))
print("\n Top 10 Job Locations:")
print(df["job_location"].value_counts().head(10))
print("\n Missing Values:")
print(df.isnull().sum())
print("\nDuplicate Rows:")
print(df.duplicated().sum())
print("\n Data Types:")
print(df.dtypes)
df=df.drop_duplicates()
df=df.dropna(axis=1,how="all")
print("\n Misiing Values:")
print(df.isnull().sum())
df["job_location"]=df["job_location"].fillna("Unknown")
df["job_skills"]=df["job_skills"].fillna("Not Specified")
df=df.dropna(subset=["salary_year_avg"])
print(df.isnull().sum())
print(df.shape)
print(df.columns.tolist())
print(df.iloc[:,0].head(10))
df=df.rename(columns={' ':'job_title'})
print(df.columns.tolist())
print("\n Top 10 Job Titles:")
print(df["job_title"].value_counts().head(10))
print("\n Top 10 Hiring Companies:")
print(df["company_name"].value_counts().head(10))
print("\n Top 10 Job Locations:")
print(df["job_location"].value_counts().head(10))
print("\n Average Salary in Year:")
print(df["salary_year_avg"].mean())
print("\nHighest Salary:")
print(df["salary_year_avg"].max())
print("\n Top 10 Highest Paying Roles:")
top_roles=(df.groupby("job_title")["salary_year_avg"].mean().sort_values(ascending=False).head(10))
print(top_roles)
skills=df["job_skills"]
skills=skills.str.replace("[","",regex=False)
skills=skills.str.replace("]","",regex=False)
skills=skills.str.replace("","",regex=False)
all_skills=skills.str.split(",").explode()
all_skills=all_skills.str.strip()
print("\n Top 20 skills:")
print(all_skills.value_counts().head(20))
import matplotlib.pyplot as plt
top_jobs= df["job_title"].value_counts().head(10)
plt.figure(figsize=(10,5))
top_jobs.plot(kind="bar")
plt.title("Top 10 Job Titles")
plt.xlabel("Job Titles")
plt.ylabel("Number of Jobs")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
top_roles=(df.groupby("job_title")["salary_year_avg"].mean().sort_values(ascending=False).head(10))
plt.figure(figsize=(10,5))
top_roles.plot(kind="bar")
plt.title("Top 10 Highest Paying Roles")
plt.xlabel("Job Title")
plt.ylabel("Average Salary")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
plt.figure(figsize=(10,5))
all_skills.value_counts().head(10).plot(kind="bar")
plt.title("Top 10 Most Demanded Skills")
plt.xlabel("skills")
plt.ylabel("Demanded Count")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()
df.to_csv("cleaned_job_data.csv",index=False)


                                                           